### ISSUE TITLE
Error in training code

### ISSUE THREAD

**Issue by smethnani** [klightz/PSF#2]
Hi, I've just read your paper and am trying to run the code but the training code in train_flow.py doesn't appear to be working. I notice a break command [here](https://github.com/klightz/PSF/blob/3920bb25c1919ee0edfd640a14e8c660027714b6/train_flow.py#L370) before the loss is computed which triggers an error when removed. Is there a known reason for this? Do you have any suggestions to succesfully train the model? Thanks!

**Comment by smethnani** [comment]
For the record, the error was a `torch.cuda.OutOfMemoryError: CUDA out of memory` error which was fixed by lowering the batch size. Not sure if the break command there is an accident but removing it lets the model compute the losses now. Thanks!

**Comment by smethnani** [comment]
Keeping this open to ask if there's a reason for the break command

**Comment by klightz** [comment]
Thanks for pointing this out, it’s for debugging and I have removed it away.
